sudo: required
language: c
services:
  - docker
before_install:
  - docker pull bitcraze/builder
script:
  # Build CF basic
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build

  # Build CF with "all" features enabled
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build clean
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build DEBUG=1 "EXTRA_CFLAGS=-DCALIBRATED_LED_MORSE -DIMU_TAKE_ACCEL_BIAS -DIMU_MPU6500_DLPF_256HZ -DMADWICK_QUATERNION_IMU -DDEBUG_QUEUE_MONITOR -DENABLE_BQ_DECK -DSITAW_ENABLED -DOW_WRITE_TEST -DOW_READ_TEST"

  # Build CF with kalman estimator
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build clean
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build DEBUG=1 ESTIMATOR=kalman SENSORS=task

  ###  Q2

  # Build Q2 basic
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build clean
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build VEH=Q2

  # Build Q2 with "all" features enabled
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build clean
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build VEH=Q2 DEBUG=1 "EXTRA_CFLAGS=-DCALIBRATED_LED_MORSE -DIMU_TAKE_ACCEL_BIAS -DIMU_MPU6500_DLPF_256HZ -DMADWICK_QUATERNION_IMU -DDEBUG_QUEUE_MONITOR -DENABLE_BQ_DECK -DSITAW_ENABLED -DOW_WRITE_TEST -DOW_READ_TEST"

  # Build Q2 with kalman estimator
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build clean
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build VEH=Q2 DEBUG=1 ESTIMATOR=kalman SENSORS=task

  # Build Q2 with manipulator
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build clean
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build VEH=Q2 DEBUG=1 "EXTRA_CFLAGS=-DENABLE_Q2_ARM"

notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    slack: irl-uiuc:ITyhS3YwmFkqtup3WOvsBfuR
    on_success: never
    on_failure: change
